'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Online_Menu
    Public Property id As Integer
    Public Property text As String
    Public Property iconCls As String
    Public Property parent_id As Nullable(Of Integer)
    Public Property className As String

    Public Overridable Property Online_Groups As ICollection(Of Online_Groups) = New HashSet(Of Online_Groups)

End Class
