'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Online_Groups
    Public Property id As Integer
    Public Property name As String

    Public Overridable Property Online_User As ICollection(Of Online_User) = New HashSet(Of Online_User)
    Public Overridable Property Online_Menu As ICollection(Of Online_Menu) = New HashSet(Of Online_Menu)

End Class
