'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Online_User
    Public Property id As Integer
    Public Property name As String
    Public Property userName As String
    Public Property password As String
    Public Property email As String
    Public Property picture As String
    Public Property Group_id As Integer

    Public Overridable Property Online_Groups As Online_Groups

End Class
