/*
 * File: app/view/publicControl/cmbProjectType_btn.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CloudRealEstate.view.publicControl.cmbProjectType_btn', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.cmbprojecttype_btn',

    trigger2Cls: 'x-form-search-trigger',
    fieldLabel: 'Project Type',
    labelWidth: 80,
    displayField: 'Project_TypeCode',
    queryMode: 'local',
    valueField: 'Project_TypeId',

    initComponent: function() {
        var me = this;
        Ext.applyIf(me, {
            listeners: {
                render: function (c) {
                    //  c.triggerCell.elements[1].set({ 'data-qtip': c.qtip });
                }
            },
            listConfig: {
                getInnerTpl: function() {

                    return '<table width="100%">'+
                        '<tr>'+
                        '<td style="vertical-align:top;width:100%">'+
                        '<div><span style="font-weight:bold;left: 0;right: auto;position: absolute;">{Project_TypeCode}</span><span style="float:right;color:blue">{Project_TypeName}</span></div>'+
                        '</td>'+
                        '</tr>'+
                        '</table>';
                },
                listeners: {
                    resize: {
                        fn: function(el){
                            // console.log(el);
                            // console.log(el.width);
                            this.newwid=el.width;


                        }
                    }
                },
                resizable: true,
                minWidth: 300,
                width: 300
            }
        });
        me.addEventAndLoadStore(me);
        me.callParent(arguments);
    },

    addEventAndLoadStore: function(config) {
        var store= Ext.create("CloudRealEstate.store.SettingMain.ProjectType").load();
        config.store=store;
        return config;
    }


});