/*
 * File: app/model/SettingMain/ProjectMain.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CloudRealEstate.model.SettingMain.ProjectMain', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'Project_Id'
        },
        {
            name: 'Company_Id'
        },
        {
            name: 'Project_Code'
        },
        {
            name: 'Project_Name'
        },
        {
            name: 'Address'
        },
        {
            name: 'CountryCode'
        },
        {
            name: 'City_id'
        },
        {
            name: 'CityCode'
        },
        {
            name: 'CityName'
        },
        {
            name: 'Region_Id'
        },
        {
            name: 'Region_Code'
        },
        {
            name: 'Region_Name'
        },
        {
            name: 'Zone_Id'
        },
        {
            name: 'Zone_Code'
        },
        {
            name: 'Zone_Name'
        },
        {
            name: 'OCompany_IdPj'
        },
        {
            name: 'OCompanyCode'
        },
        {
            name: 'OCompanyName'
        },
        {
            name: 'Project_TypeId'
        },
        {
            name: 'Project_TypeCode'
        },
        {
            name: 'Project_TypeName'
        },
        {
            name: 'Description'
        },
        {
            name: 'location_lat_long'
        },
        {
            name: 'lat'
        },
        {
            name: 'long'
        },
        {
            name: 'Active'
        },
        {
            name: 'User_Id'
        },
        {
            name: 'Entry_Date'
        },
        {
            name:'OpTypeLst'
        }
    ]
});