/*
 * File: app/model/SettingMain/ProjectSub.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CloudRealEstate.model.SettingMain.ProjectSub', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    fields: [
        {
            name: 'Project_IdSub'
        },
        {
            name: 'Project_Id'
        },
        {
            name: 'Company_Id'
        },
        {
            name: 'Project_Type_OptionId'
        },
        {
            name: 'ProjectOption_Code'
        },
        {
            name: 'ProjectOption_Name'
        },
        {
            name: 'TotalUnitUsed'
        },
        {
            name: 'ApplyManage'
        },
        {
            name: 'Notes'
        },
        {
            name: 'User_Id'
        },
        {
            name: 'Entry_Date'
        },
        {
            name: 'Computer_name'
        }
    ],

    proxy: {
        type: 'ajax',
        actionMethods: {
            read: 'POST',
            create: 'POST',
            update: 'POST',
            destroy: 'POST'
        },
        api: {
            read: 'SettingMain/get_Project_Sub',
            update: 'SettingMain/Project_Sub_Insert',
            create: 'SettingMain/Project_Sub_Insert',
            destroy: 'SettingMain/Project_Sub_Insert'
        },
        url: 'SettingMain/get_Project_Sub',
        reader: {
            type: 'json'
        },
        writer: {
            type: 'json'
        }
    }
});