/*
 * File: app/model/SettingMain/ProjectGallery.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CloudRealEstate.model.SettingMain.ProjectGallery', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'Pj_Gallery_Id'
        },
        {
            name: 'Project_Id'
        },
        {
            name: 'Company_Id'
        },
        {
            name: 'Pj_img_Code'
        },
        {
            name: 'Pj_img_path'
        },
        {
            name: 'Relation_Id'
        },
        {
            name: 'alt_Image'
        },
        {
            name: 'Description_Image'
        },
        {
            name: 'Active'
        },
        {
            name: 'User_Id'
        },
        {
            name: 'Entry_Date'
        },
        {
            name: 'Computer_name'
        }
    ]
});