/*
 * File: app/model/SettingMain/Region.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CloudRealEstate.model.SettingMain.Region', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'Region_Id'
        },
        {
            name: 'Company_Id'
        },
        {
            name: 'Country_Code'
        },
        {
            name: 'Region_Code'
        },
        {
            name: 'Region_Name'
        },
        {
            name: 'comments'
        },
        {
            name: 'Longitude'
        },
        {
            name: 'Latitude'
        },
        {
            name: 'Region_Properties'
        },
        {
            name: 'Active'
        },
        {
            name: 'User_Id'
        },
        {
            name: 'Last_Modified'
        },
        {
            name: 'Date_Entry'
        }
    ]
});