/*
 * File: app/view/SettingMain/ProjectTypeOptions.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CloudRealEstate.view.SettingMain.ProjectTypeOption', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.projecttypeoption',

    requires: [
        'CloudRealEstate.view.SettingMain.ProjectTypeOptionsHdr',
        'CloudRealEstate.view.SettingMain.ProjectTypeOptionsGrd',
        'Ext.form.Panel'
    ],

    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'projecttypeoptionsHdr',
                    region: 'north'
                },
                {
                    xtype: 'projecttypeoptionsGrd',
                    region: 'center'
                }
            ]
        });

        me.callParent(arguments);
    }

});